POSTGRES_URI = "postgres://root:12345678@localhost:5432/quiero_trabajar"
PROJECT_NAME = "Quiero Trabajar"
VERSION = "1.0"
SECRET_KEY = "74caebae5d66e58f1edba178f0ab14d82dd45c7c908ea2a4e6f456926f7f0721"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30

[development]
DEBUG = "True"
UVICORN_RELOAD = "True"

[production]
DEBUG = "False"