"""

Revision ID: 0eb8e4f6d335
Revises: e91b2dc59e4e
Create Date: 2021-02-18 15:20:53.224162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb8e4f6d335'
down_revision = 'e91b2dc59e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
