"""

Revision ID: 3ad750094f96
Revises: c5ee80564d70
Create Date: 2021-02-18 14:25:26.320272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad750094f96'
down_revision = 'c5ee80564d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthday', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('city', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('confirm_email', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=25), nullable=False))
    op.add_column('users', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(length=16), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=120), nullable=False))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('website', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'website')
    op.drop_column('users', 'username')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'password')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'email')
    op.drop_column('users', 'date_created')
    op.drop_column('users', 'country')
    op.drop_column('users', 'confirm_email')
    op.drop_column('users', 'city')
    op.drop_column('users', 'birthday')
    # ### end Alembic commands ###
