"""otra prueba

Revision ID: 670520064726
Revises: 38c06b372632
Create Date: 2021-02-18 22:32:49.386030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '670520064726'
down_revision = '38c06b372632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('jobs_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'employee', 'jobs', ['jobs_id'], ['employee_id'])
    op.drop_constraint('jobs_employee_id_fkey', 'jobs', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('jobs_employee_id_fkey', 'jobs', 'employee', ['employee_id'], ['id'])
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'jobs_id')
    # ### end Alembic commands ###
