"""foreign key correcto

Revision ID: 7c5d32848273
Revises: bec5f29f3c2a
Create Date: 2021-02-18 22:39:55.742264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c5d32848273'
down_revision = 'bec5f29f3c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
