"""

Revision ID: 95561ef305f8
Revises: ffe2e7fe7a67
Create Date: 2021-02-18 15:11:25.291283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95561ef305f8'
down_revision = 'ffe2e7fe7a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
