"""prueba foreign

Revision ID: d48901a3713e
Revises: a284d6c541d5
Create Date: 2021-02-18 22:12:56.170839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd48901a3713e'
down_revision = 'a284d6c541d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employee_jobs_id_fkey', 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'jobs', ['jobs_id'], ['employee'])
    op.add_column('jobs', sa.Column('employee', postgresql.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'employee')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key('employee_jobs_id_fkey', 'employee', 'jobs', ['jobs_id'], ['id'])
    # ### end Alembic commands ###
