"""

Revision ID: e91b2dc59e4e
Revises: 95561ef305f8
Create Date: 2021-02-18 15:12:06.000114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e91b2dc59e4e'
down_revision = '95561ef305f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
