"""

Revision ID: ffe2e7fe7a67
Revises: 3ad750094f96
Create Date: 2021-02-18 15:07:27.952478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe2e7fe7a67'
down_revision = '3ad750094f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
